import turtle
turtle. shape("turtle")
turtle.fillcolor("yellow")
turtle.pensize(5)
turtle.pencolor("yellow")
turtle.begin_fill()
turtle. forward (100)
turtle. right(90)
turtle. forward(100)
turtle. right(90)
turtle. forward(100)
turtle. right(90)
turtle. forward(100)
turtle. mainloop()